name: Build and deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_DEPLOY_IP}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd fed22d-agila-planning-poker-ekenaset/
            git checkout main
            git pull
            docker-compose up -d --build
            echo "Deployment successful"
